### ISSUE TITLE
Error 0x80004005: Unspecified error

### ISSUE THREAD

**Issue by just2102** [Russifiers-for-Humans/Europa-Universalis-4-DLC#3]
![image](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/assets/88230737/cb6c3781-db53-4a1a-af4d-54bb50870f8e)

**Comment by 55TeMeR55** [comment]
В чём проблема? При распаковке из exe или из zip?

**Comment by just2102** [comment]
Да, не даёт распаковать. Win 11

> В чём проблема? При распаковке из exe или из zip?

**Comment by 55TeMeR55** [comment]
Что то возможно держит этот файл, мб антивирус или игра запущенная, перезагрузитесь и попробуйте не запуская ничего установить еще раз, ну или скипните  это, а [отсюда распакуйте](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/releases/download/1.37/crack.zip), я сам на w10 такого не видел.
