### ISSUE TITLE
404 This is not the web page you are looking for

### ISSUE THREAD

**Issue by angryWilly** [Russifiers-for-Humans/Europa-Universalis-4-DLC#4]
Попытался скачать архивы, которые были приведены в релизе (Архив 1, Архив 2, Архив 3), но безуспешно редеректить на страничку-заглушку.
Можно ли обновить архивы или ссылки на них? ;(

**Comment by 55TeMeR55** [comment]
[Архив 1](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/releases/download/1.37/DLC-Europa-Universalis-4.zip.001)
[Архив 2](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/releases/download/1.37/DLC-Europa-Universalis-4.zip.002)
[Архив 3](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/releases/download/1.37/DLC-Europa-Universalis-4.zip.003)
[Архив 4](https://github.com/Russifiers-for-Humans/Europa-Universalis-4-DLC/releases/download/1.37/DLC-Europa-Universalis-4.zip.004)
