### ISSUE TITLE
Неверный хэш файла

### ISSUE THREAD

**Issue by Revanhol** [Russifiers-for-Humans/Europa-Universalis-4-DLC#5]
![image](https://github.com/user-attachments/assets/2c945340-a726-47ee-9f08-445e210350a2)

**Comment by 55TeMeR55** [comment]
Здравствуйте! Вы уже скачали последнюю версию автоустановщика? Я проверил, всё вроде записано правильно, и файл имеет верный хэш. Рекомендую попробовать запустить установку заново — возможно, при скачивании произошла ошибка.
![1](https://github.com/user-attachments/assets/2d5eb577-afdc-49e7-82fc-e68111a7fb65)
![2](https://github.com/user-attachments/assets/50626aa7-bc7e-4f94-b272-2fa87b3f1eef)

**Comment by Revanhol** [comment]
Да я уже вручную поставил
